name: Build & Deploy Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: |
          if [ -f package.json ]; then npm install; fi

      - run: |
          if [ -f package.json ] && npm run | grep -q build; then npm run build; fi

      - uses: actions/deploy-pages@v5
        with:

          artifact_name: github-pages
